### PR TITLE
Adding script to dump tweets from a Twitter user

### PR DESCRIPTION
**Pull request by cbjuan**
### Summary
As requested by #3, this PR adds support to get the tweets of a user from the social network Twitter. The first script added downloads the last 3240 tweets from the user selected. 

### Details and comments
We can add more scripts and tools to retrieve data from Twitter or other sources to feed the neural networks.

### CODE REVIEW

**Comment by cbjuan** [comment]
The Travis-CI PR check fails because the master branch does not have a folder called `test` 🤷‍♂️

**Comment by cbjuan** [comment]
Travis seems to be working properly now in the case of PRs 🙂

**Comment by hmorillo** [comment]
Reviewing the travis output I think that something went wrong with the condicional:
```
$ if (( "${TRAVIS_PULL_REQUEST}" = "false" )); then
    git pull --rebase #resolve conflicts here
fi
```
This command generates the following error:

`/home/travis/.travis/job_stages: line 98: ((: 5 = false : attempted assignment to non-variable (error token is "= false ")`

I think the problem is with the comparison symbol. `=` is an assignment.  I change it for "==" and now, if I not wrong, it has to work properly.

**Comment by cbjuan** [comment]
Sure, it seems good to me!

**Pull request merged**
